<?php

$GLOBALS['TL_LANG']['tl_user']['tfa_title'] = 'Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_exception_invalid'] = 'The entered code is invalid.';

$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate'] = 'Deactivate Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate_explanation'] = 'To verify please type in the current code.';

$GLOBALS['TL_LANG']['tl_user']['tfaChange'][0] = 'Force two-factor reset';
$GLOBALS['TL_LANG']['tl_user']['tfaChange'][1] = 'Make the user reset their two-factor authentication upon the next login.';

$GLOBALS['TL_LANG']['tl_user']['tfaReset'][0] = 'Reset Two-Factor Settings';
$GLOBALS['TL_LANG']['tl_user']['tfaReset'][1] = 'Resets the two-factor authentication settings of this user, disabling 2FA for them.';

$GLOBALS['TL_LANG']['tl_user']['tfa_explanation'] = 'Please scan this QR code with a compatible app, such as the <strong>Google Authenticator</strong> (<a href="https://itunes.apple.com/app/google-authenticator/id388497605" target="_blank">iOS</a>/<a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank">Android</a>) und type in the code generated by the app afterwards.';
$GLOBALS['TL_LANG']['tl_user']['tfa_activated'] = 'You have already activated two-factor authentication. Please keep your authenticator app at the ready when you log into Contao in the future.';
$GLOBALS['TL_LANG']['tl_user']['tfa_token'] = 'Code generated by your app';
$GLOBALS['TL_LANG']['tl_user']['tfa_help_input'] = 'Please enter the code generated by your authenticator app.';

$GLOBALS['TL_LANG']['tl_user']['tfa_code'] = 'Code';