<?php

$GLOBALS['TL_LANG']['tl_user']['tfa_title'] = 'Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_exception_invalid'] = 'The entered code is invalid.';

$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate'] = 'Deactivate Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate_explanation'] = 'To verify please type in the current code.';

$GLOBALS['TL_LANG']['tl_user']['tfaChange'][0] = 'Force two-factor reset';
$GLOBALS['TL_LANG']['tl_user']['tfaChange'][1] = 'Make the user reset his two-factor authentication upon the next login.';

$GLOBALS['TL_LANG']['tl_user']['tfaReset'][0] = 'Reset Two-Factor Settings';
$GLOBALS['TL_LANG']['tl_user']['tfaReset'][1] = 'Resets the two-factor authentication settings of this user, disabling 2FA for him.';

$GLOBALS['TL_LANG']['tl_user']['tfa_explanation'] = 'To activate two-factor authentication for your account please scan the QR code with a compatible app such as <strong>Google Authenticator</strong> (available for iOS and Android) and type in the generated code afterwards.';
$GLOBALS['TL_LANG']['tl_user']['tfa_activated'] = 'You have already activated two-factor authentication. Please keep your authenticator app at the ready when you log into Contao in the future.';
$GLOBALS['TL_LANG']['tl_user']['tfa_token'] = 'Code generated by your app';