<?php

$GLOBALS['TL_LANG']['tl_user']['tfa_title'] = 'Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_exception_invalid'] = 'The entered code is invalid.';

$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate'] = 'Deactivate Two-Factor Authentication';
$GLOBALS['TL_LANG']['tl_user']['tfa_deactivate_explanation'] = 'To verify please type in the current code.';

$GLOBALS['TL_LANG']['tl_user']['tfa_explanation'] = 'To activate two-factor authentication for your account please scan the QR code with a compatible app such as <strong>Google Authenticator</strong> (available for iOS and Android) and type in the generated code afterwards.';
$GLOBALS['TL_LANG']['tl_user']['tfa_activated'] = 'You have already activated two-factor authentication. Please keep your authenticator app at the ready when you log into Contao in the future.';
$GLOBALS['TL_LANG']['tl_user']['tfa_token'] = 'Code generated by your app';